FROM apache/spark:4.1.1-scala2.13-java21-python3-r-ubuntu

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends software-properties-common && \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y --no-install-recommends python3.12 python3.12-venv python3.12-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ENV PYSPARK_PYTHON=python3.12

USER spark
